---
title : 'Ettin'
output : html_notebook
---

```{r, include = FALSE, warning = FALSE}

# initialize environment
if (!is.null(dev.list())) dev.off()
rm(list = ls())
cat('\014')

```

```{r, warning = FALSE}

# library(remotes)
# install_github('willzywiec/criticality', auth_token = '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', quiet = TRUE)
# library(criticality)

remove.packages('criticality')

library(devtools)
library(roxygen2)

# setwd('C:/Users/Will/Documents/GitHub/criticality')
setwd('/Users/will/Documents/GitHub/criticality')

document()

# setwd('C:/Users/Will/Documents/GitHub')
setwd('/Users/will/Documents/GitHub')

install('criticality', upgrade = 'never')

# check('criticality')

```

```{r}

# set variable
# ext.dir <- 'C:/Users/Will/Documents/GitHub/criticality/data'
ext.dir <- '/Users/will/Documents/GitHub/criticality/data'

# tabulate data
dataset <- Tabulate(
  code = 'mcnp',
  ext.dir = ext.dir)

```

```{r, warning = FALSE}

# build metamodel
# metamodel <- Split(
#   dataset = dataset,
#   replot = FALSE,
#   ext.dir = '/Users/will/Desktop/example')

# build metamodel
metamodel <- NN(
  batch.size = 128,
  epochs = 10,
  ensemble.size = 1,
  replot = FALSE,
  ext.dir = ext.dir,
  training.dir = ext.dir)

```

```{r, warning = FALSE}

# set variable
facility <- 'facility'

# build Bayesian network
bn <- BN(
  facility = facility,
  ext.dir = ext.dir)

# estimate risk
risk <- Risk(
  dist = 'gamma',
  facility = facility,
  keff.cutoff = 0.5,
  metamodel = metamodel,
  risk.pool = 10,
  sample.size = 1e+05,
  ext.dir = ext.dir)

```
