---
title : 'R Notebook'
output : html_notebook
---

# search.Rmd
#
# William Zywiec

```{r, include = FALSE, warning = FALSE}

# initialize environment
if (!is.null(dev.list())) dev.off()
rm(list = ls())
cat('\014')

```

```{r, warning = FALSE}

# set variables
code <- 'mcnp'
external.dir <- 'D:/7.8M' # 'D:/Apricorn'
source.dir <- 'D:/Dropbox/GWU/R/source'
data.dir <- paste0(external.dir, '/data')

# load function
source(paste0(source.dir, '/tabulate.R'))

# tabulate data
dataset <- Tabulate(code, data.dir, source.dir)

```

```{r, warning = FALSE}

library(magrittr)

# set variables
batch.size <- 8192
ensemble.size <- 1
epochs <- 100
loss <- 'sse'
opt.alg <- 'adamax'
learning.rate <- 0.00075
val.split <- 0.2
replot <- FALSE
search.dir <- paste0(external.dir, '/search')

# load function
source(paste0(source.dir, '/nn.R'))

grid <- expand.grid(
  8192,
  512, # c(256, 512)
  512, # c(256, 512)
  512, # c(256, 512)
  256,
  c(128, 256),
  c(32, 64, 128))

layers <- character()
test.mae <- numeric()

# perform grid search
for (i in 1:nrow(grid)) {
  if (i != 1) cat('\n\n')
  layers[i] <- paste0(
    as.character(grid[i, 1]), '-',
    as.character(grid[i, 2]), '-',
    as.character(grid[i, 3]), '-',
    as.character(grid[i, 4]), '-',
    as.character(grid[i, 5]), '-',
    as.character(grid[i, 6]), '-',
    as.character(grid[i, 7]))
  test.dir <- paste0(search.dir, '/', layers[i], '/', learning.rate)
  metamodel <- NN(dataset, batch.size, ensemble.size, epochs, layers[i], loss, opt.alg, learning.rate, val.split, replot, source.dir, test.dir)
  test.mae[i] <- metamodel[[2]]$value
  cat('\nBest Ensemble Test MAE: ', min(test.mae) %>% sprintf('%.6f', .), ' (', layers[which.min(test.mae)], ')', sep = '')
}

setwd(search.dir)

write.csv(data.frame(layers = layers, test.mae = test.mae), file = 'test-mae.csv', row.names = FALSE)

```
